# Dependencies
markdown:            kramdown
# highlighter:         pygments
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Bookworm
tagline:             'textual experimentation'
description:         'An exploration of text analytics and fiction.'
url:                 http://bookworm.davidlday.com
baseurl:             
paginate:            5
disqus_shortname:    bookworm-analytics

# About/contact
author:
  name:              David L. Day
  url:               https://twitter.com/dday376
  email:             david@davidlday.com

# Custom vars
version:             0.0.1
google_analytics:    UA-34915921-3

# jekyll-toc-generator options
# https://github.com/dafi/jekyll-toc-generator
minItemsToShowToc:   0
anchorPrefix:        toc-
showToggleButton:    false

# Plugins
plugins: ["jekyll-paginate"]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  syntax_highlighter_opts:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class
